language: elixir
elixir:
- 1.10
otp_release:
- 22.0
sudo: false
before_script:
- mix deps.get
script:
- mix test
before_install:
- openssl aes-256-cbc -K $encrypted_ceeba745adea_key -iv $encrypted_ceeba745adea_iv
  -in config.exs.enc -out config/config.exs -d
